### ISSUE TITLE
Python3.6 with nornir2.0 won't import InitNornir

### ISSUE THREAD

**Issue by achhabr1** [nornir-automation/nornir#330]
I am facing below errors while working with nornir2.0 and python3.6 on RHEL environment 

>>> import nornir
>>> from nornir.core import InitNornir
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'InitNornir'
>>> from nornir.core import InitNornir
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'InitNornir'
>>> from nornir.plugins.tasks.networking import netmiko_file_transfer 
>>> from nornir.core import InitNornir                                
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'InitNornir'
>>>

**Comment by ktbyers** [comment]
@achhabr1 On Nornir 2.0, InitNornir is not in core any more:

```
>>> import nornir
>>> nornir.__version__
'2.0.0'
>>> from nornir import InitNornir
```
